Repository CodIN-INU/codin-lecture-api, pull requests merged in 2025-09, with the labels that each got.

#22 fix : search error
  src/main/java/inu/codin/codin/domain/elasticsearch/document/LectureDocument.java
  src/main/java/inu/codin/codin/domain/elasticsearch/indexer/LectureStartupIndexer.java
  src/main/java/inu/codin/codin/domain/elasticsearch/service/LectureElasticService.java
  src/main/java/inu/codin/codin/domain/lecture/controller/LectureController.java
  src/main/java/inu/codin/codin/domain/lecture/dto/LectureDetailResponseDto.java
  src/main/java/inu/codin/codin/domain/lecture/dto/LecturePreviewResponseDto.java
  src/main/java/inu/codin/codin/domain/lecture/entity/Lecture.java
  src/main/java/inu/codin/codin/domain/lecture/repository/LectureSearchRepositoryCustom.java
  src/main/java/inu/codin/codin/domain/lecture/repository/LectureSearchRepositoryImpl.java
  src/main/java/inu/codin/codin/domain/lecture/service/LectureService.java
  src/main/java/inu/codin/codin/global/common/exception/GlobalExceptionHandler.java
  src/main/resources/elasticsearch/settings/lecture-settings.json
Labels: enhancement

#23 fix : elasticsearch add missing
  Dockerfile.es
  elastic-docker-compose.yml
  src/main/java/inu/codin/codin/domain/elasticsearch/service/LectureElasticService.java
  src/main/java/inu/codin/codin/domain/review/service/ReviewService.java
Labels: enhancement

#27 fix: Evaluation 컨버터 추가 및 Type Enumerated 삭제
  src/main/java/inu/codin/codin/domain/lecture/converter/EvaluationConverter.java
  src/main/java/inu/codin/codin/domain/lecture/entity/Evaluation.java
  src/main/java/inu/codin/codin/domain/lecture/entity/Lecture.java
Labels: bug

#25 refactor: add NPE safe code
  src/main/java/inu/codin/codin/domain/elasticsearch/service/LectureElasticService.java
  src/main/java/inu/codin/codin/global/common/exception/GlobalExceptionHandler.java
Labels: enhancement

#28 fix: #25 #27 변경사항 적용
  src/main/java/inu/codin/codin/domain/elasticsearch/service/LectureElasticService.java
  src/main/java/inu/codin/codin/domain/lecture/converter/EvaluationConverter.java
  src/main/java/inu/codin/codin/domain/lecture/entity/Evaluation.java
  src/main/java/inu/codin/codin/domain/lecture/entity/Lecture.java
  src/main/java/inu/codin/codin/global/common/exception/GlobalExceptionHandler.java
Labels: bug, enhancement
